// <auto-generated />
namespace DotNetAppSqlDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddProperty8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProperty8));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241522170_AddProperty8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
